spring:
  application:
    name: email-sender

  mail:
    ##### SMTP configuration #####
    host: smtp.gmail.com
    port: 587
    username: asharkhan.eidiko@gmail.com
    password: ${APP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

    #### IMAP configuration ######
    imap:
      host: imap.gmail.com
      port: 993
      user: asharkhan.eidiko@gmail.com
      password: ${APP_PASSWORD}
      protocol: imaps
      ssl.enable: true


server:
  port: 9090
