spring:
  application:
    name: Java Mail App

#### SMTP Configuration ####

  mail:
    host: smtp.gmail.com
    port: 587
    username: asharkhan.eidiko@gmail.com
    password: ${APP_PASSWORD}
    properties.mail.smtp:
      auth: true
      starttls.enable: true

#### IMAP Configuration ####

    imap:
      host: imap.gmail.com
      port: 993
      user: asharkhan.eidiko@gmail.com
      password: ${APP_PASSWORD}
      protocol: imaps
      ssl.enable: true

#### Webserver Port Configuration ####

server:
  port: 9090


