#spring boot and data jpa config
spring:
  application:
    name: First Boot
  config:
    import: "classpath:variables.yml"
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: ashar
    password: Ashark@007
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9090

#swagger config

springdoc.swagger-ui:
  path: /api
  layout: BaseLayout


#actuators
# Expose all actuator endpoints

management.endpoints.web.exposure.include: "*"
